import { useLocation, useNavigate } from "react-router-dom";
import {
  Brain,
  ArrowLeft,
  CircleCheckBig,
  TriangleAlert,
  Route,
  Copy,
  Home,
  Sparkles,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { motion } from "framer-motion";

function Report() {
  const { state } = useLocation();
  const navigate = useNavigate();

  const report = state?.report;

  if (!report) {
    return (
      <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center relative overflow-hidden">
        <div className="absolute inset-0 overflow-hidden -z-10">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 h-[500px] w-[500px] rounded-full bg-indigo-600/20 blur-[170px]" />
          <div className="absolute bottom-0 right-0 h-[350px] w-[350px] rounded-full bg-cyan-500/10 blur-[140px]" />
        </div>

        <motion.div
          initial={{ opacity: 0, y: 25 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45 }}
          className="w-full max-w-xl mx-6 rounded-3xl border border-slate-800 bg-slate-900/70 backdrop-blur-xl p-10 text-center"
        >
          <Brain size={70} className="mx-auto text-indigo-400" />

          <h1 className="text-4xl md:text-5xl font-bold mt-8">
            No Report Available
          </h1>

          <p className="mt-5 text-slate-400 leading-8">
            Complete a decision analysis to generate your personalized AI
            report.
          </p>

          <button
            onClick={() => navigate("/")}
            className="mt-10 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-8 py-3 font-semibold"
          >
            Go Home
          </button>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 text-white relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden -z-10">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 h-[500px] w-[500px] rounded-full bg-indigo-600/20 blur-[170px]" />
        <div className="absolute bottom-0 right-0 h-[350px] w-[350px] rounded-full bg-cyan-500/10 blur-[140px]" />
      </div>

      <motion.div
        initial={{ opacity: 0, y: 25 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45 }}
        className="max-w-6xl mx-auto px-6 py-16"
      >
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-indigo-400 hover:text-indigo-300"
        >
          <ArrowLeft size={18} />
          Home
        </button>

        <div className="mt-10 flex flex-col md:flex-row md:items-center gap-6">
          <div className="rounded-3xl bg-indigo-600/20 p-6">
            <Brain className="text-indigo-400" size={50} />
          </div>

          <div>
            <h1 className="text-4xl md:text-5xl font-bold">
              AI Decision Report
            </h1>

            <p className="mt-3 text-slate-400 text-lg">
              Personalized recommendations generated by DecideWise AI.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-12">
          {[
            {
              icon: <Sparkles className="text-indigo-400" />,
              title: "Decision Score",
              value: "AI",
            },
            {
              icon: <CircleCheckBig className="text-green-400" />,
              title: "Recommendation",
              value: "Personalized",
            },
            {
              icon: <TriangleAlert className="text-yellow-400" />,
              title: "Risk Analysis",
              value: "Included",
            },
            {
              icon: <Route className="text-cyan-400" />,
              title: "Roadmap",
              value: "Generated",
            },
          ].map((card, index) => (
            <motion.div
              key={card.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className="rounded-2xl border border-slate-800 bg-slate-900/70 backdrop-blur-xl p-6"
            >
              {card.icon}

              <h3 className="mt-4 font-semibold">{card.title}</h3>

              <p className="mt-3 text-2xl font-bold text-indigo-400">
                {card.value}
              </p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="mt-12 rounded-3xl border border-slate-800 bg-slate-900/70 backdrop-blur-xl p-10"
        >
          <div className="flex items-center gap-3 mb-8">
            <Brain className="text-indigo-400" />

            <h2 className="text-3xl font-bold">AI Analysis</h2>
          </div>

          <div
            className="
              prose
              prose-invert
              max-w-none
              break-words

              prose-headings:text-white
              prose-p:text-slate-300
              prose-strong:text-indigo-400
              prose-li:text-slate-300
              prose-a:text-indigo-400
              prose-blockquote:text-slate-300
            "
          >
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {report}
            </ReactMarkdown>
          </div>
        </motion.div>

        <div className="flex flex-col sm:flex-row gap-4 mt-12">
          <button
            onClick={() => navigate("/")}
            className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-8 py-3 font-semibold"
          >
            <Home size={18} />
            New Decision
          </button>

          <button
            onClick={() => navigator.clipboard.writeText(report)}
            className="flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-8 py-3 hover:border-indigo-500"
          >
            <Copy size={18} />
            Copy Report
          </button>
        </div>
      </motion.div>
    </div>
  );
}

export default Report;